/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/scene.gltf -tT -o Amplifier.tsx -r /assets/models 
Files: ./public/assets/models/scene.gltf [13.73KB] > scene-transformed.glb [1.09MB] (-7839%)
Author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-guitar-amplifier-free-prop-4c520860a87e43b095050b120eef7443
Title: Electric Guitar Amplifier [FREE PROP]
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Box_Box_0: THREE.Mesh;
    Speaker_Speaker_0: THREE.Mesh;
    Top_Top_0: THREE.Mesh;
    Panel_Panel_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    Speaker: THREE.MeshStandardMaterial;
    material_2: THREE.MeshStandardMaterial;
    Panel: THREE.MeshStandardMaterial;
  };
};

export function Amplifier(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/models/amplifier.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Box_Box_0.geometry}
        material={materials.material}
        position={[0, 0.255, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.681}
      />
      <mesh
        geometry={nodes.Speaker_Speaker_0.geometry}
        material={materials.Speaker}
        position={[-0.006, 0.235, 0]}
        rotation={[-Math.PI / 4, Math.PI / 2, 0]}
        scale={0.681}
      />
      <mesh
        geometry={nodes.Top_Top_0.geometry}
        material={materials.material_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.681}
      />
      <mesh
        geometry={nodes.Panel_Panel_0.geometry}
        material={materials.Panel}
        position={[0.182, 0.454, -0.325]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.681}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/amplifier.glb');
