// Auto-generated by: ./src/build/build-artifact-paths.ts
const artifactPaths = {
  Amplifier: '/assets/models/amplifier.glb',
  AssembleDate: '/assets/models/assembly-date-bubble-transformed.glb',
  AssembleTestSceneName:
    '/assets/models/assemble-test-scene-name-transformed.glb',
  CruiseDate: '/assets/models/cruise-date-bubble-transformed.glb',
  CruiseName: '/assets/models/cruise-arrival-scene-name-transformed.glb',
  CruiseOrbiter: '/assets/models/cruise-orbiter-transformed.glb',
  DashedOrbit: '/assets/models/orbit-dashed-transformed.glb',
  Debris: '/assets/models/debris-transformed.glb',
  Earth: '/assets/models/earth-transformed.glb',
  Explosion: '/assets/models/explosion-transformed.glb',
  FalconHeavyWithLogos:
    '/assets/models/falcon-heavy-with-logos-transformed.glb',
  LaunchDateModel: '/assets/models/launch-date-model-transformed.glb',
  LaunchPadModel: '/assets/models/launch-pad-model-transformed.glb',
  LaunchSceneName: '/assets/models/launch-scene-name-transformed.glb',
  Mars: '/assets/models/mars-transformed.glb',
  OrbitDate: '/assets/models/orbit-date-bubble-transformed.glb',
  OrbitName: '/assets/models/cruise-arrival-scene-name-transformed.glb',
  OrbitOrbiter: '/assets/models/orbit-orbiter-transformed.glb',
  Orbiter: '/assets/models/orbiter-transformed.glb',
  PackOrbiter: '/assets/models/pack-orbiter-transformed.glb',
  Psyche: '/assets/models/psyche-transformed.glb',
  TimeLine: '/assets/models/time-line-transformed.glb'
};
export default artifactPaths;
