// Auto-generated by: ./src/build/build-artifact-paths.ts
const artifactPaths = {
  Amplifier: '/assets/models/amplifier.glb',
  CruiseOrbiter: '/assets/models/cruise-orbiter-transformed.glb',
  DashedOrbit: '/assets/models/orbit-dashed-transformed.glb',
  Debris: '/assets/models/debris-transformed.glb',
  Earth: '/assets/models/earth-transformed.glb',
  Explosion: '/assets/models/explosion-transformed.glb',
  FalconHeavyWithLogos:
    '/assets/models/falcon-heavy-with-logos-transformed.glb',
  LaunchPadModel: '/assets/models/launch-pad-model-transformed.glb',
  Mars: '/assets/models/mars-transformed.glb',
  OrbitB: '/assets/models/orbits_animated-transformed.glb',
  OrbitC: '/assets/models/orbits_animated-transformed.glb',
  OrbitOrbiter: '/assets/models/orbit-orbiter-transformed.glb',
  Orbiter: '/assets/models/orbiter-transformed.glb',
  Orbits: '/assets/models/orbits_animated-transformed.glb',
  PackOrbiter: '/assets/models/pack-orbiter-transformed.glb',
  Psyche: '/assets/models/psyche-transformed.glb',
  TimeLine: '/assets/models/time-line-transformed.glb'
};
export default artifactPaths;
