/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/assembly-date-bubble.gltf -tT -o AssembleDate.tsx -r /assets/models --keepgroups 
Files: ./public/assets/models/assembly-date-bubble.gltf [2.6MB] > assembly-date-bubble-transformed.glb [224.98KB] (91%)
*/

import * as THREE from 'three';
import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import FactsModalTrigger from '../facts/FactsModalTrigger';

type GLTFResult = GLTF & {
  nodes: {
    TextPlus007016: THREE.Mesh;
    TextPlus007016_1: THREE.Mesh;
    TextPlus007016_2: THREE.Mesh;
    TextPlus007016_3: THREE.Mesh;
    TextPlus013007: THREE.Mesh;
    TextPlus013007_1: THREE.Mesh;
    TextPlus013007_2: THREE.Mesh;
    TextPlus013007_3: THREE.Mesh;
    TextPlus013007_4: THREE.Mesh;
    TextPlus013007_5: THREE.Mesh;
    TextPlus007009: THREE.Mesh;
    TextPlus007009_1: THREE.Mesh;
    TextPlus007009_2: THREE.Mesh;
    TextPlus007009_3: THREE.Mesh;
    TextPlus007013: THREE.Mesh;
    TextPlus007013_1: THREE.Mesh;
    TextPlus007013_2: THREE.Mesh;
    TextPlus007013_3: THREE.Mesh;
    TextPlus007013_4: THREE.Mesh;
    Cylinder002003: THREE.Mesh;
  };
  materials: {
    ['M_01___Default.008']: THREE.MeshPhysicalMaterial;
    Timeline_Bubble_Material: THREE.MeshStandardMaterial;
    Octagon_Material: THREE.MeshStandardMaterial;
    Bottom_Octagon_Material: THREE.MeshStandardMaterial;
  };
};

export function AssembleDate(props: JSX.IntrinsicElements['group']) {
  const group = useRef(null);
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/assembly-date-bubble-transformed.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.firstMove?.play();
    actions.secondMove?.play();
    actions.thirdMove?.play();
    actions.fourthMove?.play();
  }, [
    actions.firstMove,
    actions.secondMove,
    actions.thirdMove,
    actions.fourthMove
  ]);

  return (
    <group ref={group} {...props} dispose={null}>
      <FactsModalTrigger factName="firstDateRange">
        <group
          name="FirstDate"
          position={[-19.973, 8, 0.347]}
          rotation={[0, -0.583, 0]}
          scale={0.1}
        >
          <mesh
            name="TextPlus007016"
            geometry={nodes.TextPlus007016.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus007016_1"
            geometry={nodes.TextPlus007016_1.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="TextPlus007016_2"
            geometry={nodes.TextPlus007016_2.geometry}
            material={materials.Octagon_Material}
          />
          <mesh
            name="TextPlus007016_3"
            geometry={nodes.TextPlus007016_3.geometry}
            material={materials['M_01___Default.008']}
          />
        </group>
      </FactsModalTrigger>
      <FactsModalTrigger factName="fourthDateRange">
        <group
          name="FourthDate"
          position={[24.759, 8, 10.353]}
          rotation={[0, 0.583, 0]}
          scale={0.1}
        >
          <mesh
            name="TextPlus013007"
            geometry={nodes.TextPlus013007.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus013007_1"
            geometry={nodes.TextPlus013007_1.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="TextPlus013007_2"
            geometry={nodes.TextPlus013007_2.geometry}
            material={materials.Octagon_Material}
          />
          <mesh
            name="TextPlus013007_3"
            geometry={nodes.TextPlus013007_3.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus013007_4"
            geometry={nodes.TextPlus013007_4.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus013007_5"
            geometry={nodes.TextPlus013007_5.geometry}
            material={materials['M_01___Default.008']}
          />
        </group>
      </FactsModalTrigger>
      <FactsModalTrigger factName="secondDateRange">
        <group
          name="SecondDate"
          position={[-5.065, 6, 10.256]}
          rotation={[0, -0.395, 0]}
          scale={0.1}
        >
          <mesh
            name="TextPlus007009"
            geometry={nodes.TextPlus007009.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus007009_1"
            geometry={nodes.TextPlus007009_1.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="TextPlus007009_2"
            geometry={nodes.TextPlus007009_2.geometry}
            material={materials.Octagon_Material}
          />
          <mesh
            name="TextPlus007009_3"
            geometry={nodes.TextPlus007009_3.geometry}
            material={materials['M_01___Default.008']}
          />
        </group>
      </FactsModalTrigger>
      <FactsModalTrigger factName="thirdDateRange">
        <group
          name="ThirdDate"
          position={[9.931, 7, 0.181]}
          rotation={[0, 0.395, 0]}
          scale={[0.1, 0.1, 0.08]}
        >
          <mesh
            name="TextPlus007013"
            geometry={nodes.TextPlus007013.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus007013_1"
            geometry={nodes.TextPlus007013_1.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="TextPlus007013_2"
            geometry={nodes.TextPlus007013_2.geometry}
            material={materials.Octagon_Material}
          />
          <mesh
            name="TextPlus007013_3"
            geometry={nodes.TextPlus007013_3.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="TextPlus007013_4"
            geometry={nodes.TextPlus007013_4.geometry}
            material={materials['M_01___Default.008']}
          />
        </group>
      </FactsModalTrigger>
      <mesh
        name="Cylinder002003"
        geometry={nodes.Cylinder002003.geometry}
        material={materials.Timeline_Bubble_Material}
        position={[-19.957, -4, -0.278]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      />
      <mesh
        name="Cylinder002003"
        geometry={nodes.Cylinder002003.geometry}
        material={materials.Timeline_Bubble_Material}
        position={[-5, -3, 10]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      />
      <mesh
        name="Cylinder002003"
        geometry={nodes.Cylinder002003.geometry}
        material={materials.Timeline_Bubble_Material}
        position={[9.5, -4, -0.278]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      />
      <mesh
        name="Cylinder002003"
        geometry={nodes.Cylinder002003.geometry}
        material={materials.Timeline_Bubble_Material}
        position={[24.56, -4, 9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/assembly-date-bubble-transformed.glb');
