/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/assembly-test-dates.gltf -tT -o AssembTestDates.tsx -r /assets/models 
Files: ./public/assets/models/assembly-test-dates.gltf [41.73KB] > assembly-test-dates-transformed.glb [183.86KB] (-341%)
Author: ajd6735 (https://sketchfab.com/ajd6735)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/assembly-date-bubble-1d475a127167411abe1958429d1e3346
Title: assembly-date-bubble
*/

import * as THREE from 'three';
import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_28: THREE.Mesh;
  };
  materials: {
    ['M_01___Default.008']: THREE.MeshPhysicalMaterial;
    Timeline_Bubble_Material: THREE.MeshStandardMaterial;
    Octagon_Material: THREE.MeshStandardMaterial;
    Bottom_Octagon_Material: THREE.MeshStandardMaterial;
  };
};

export function AssembTestDates(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/assembly-test-dates-transformed.glb'
  ) as GLTFResult;
  const group = useRef(null);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.FirstDateAction?.play();
    actions.SecondDateAction?.play();
    actions.ThirdDateAction?.play();
    actions.FirstDateAction?.play();
  });

  return (
    <group ref={group} {...props}>
      <group name="GLTF_SceneRootNode">
        <group
          name="FirstDate_0"
          position={[-20, 5, -5]}
          rotation={[0, 0.45, 0]}
          scale={0.1}
        >
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="Object_5"
            geometry={nodes.Object_5.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="Object_6"
            geometry={nodes.Object_6.geometry}
            material={materials.Octagon_Material}
          />
        </group>
        <group
          name="FourthDate_1"
          position={[36, 5, -5]}
          rotation={[0, 0, 0]}
          scale={0.1}
        >
          <mesh
            name="Object_9"
            geometry={nodes.Object_9.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="Object_10"
            geometry={nodes.Object_10.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="Object_11"
            geometry={nodes.Object_11.geometry}
            material={materials.Octagon_Material}
          />
        </group>
        <group
          name="SecondDate_2"
          position={[-1.75, 3, 2]}
          rotation={[0, 0, 0]}
          scale={0.1}
        >
          <mesh
            name="Object_16"
            geometry={nodes.Object_16.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="Object_17"
            geometry={nodes.Object_17.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="Object_18"
            geometry={nodes.Object_18.geometry}
            material={materials.Octagon_Material}
          />
        </group>
        <group
          name="ThirdDate_3"
          position={[18, 3, 2]}
          rotation={[0, 0, 0]}
          scale={[0.1, 0.1, 0.075]}
        >
          <mesh
            name="Object_21"
            geometry={nodes.Object_21.geometry}
            material={materials['M_01___Default.008']}
          />
          <mesh
            name="Object_22"
            geometry={nodes.Object_22.geometry}
            material={materials.Timeline_Bubble_Material}
          />
          <mesh
            name="Object_23"
            geometry={nodes.Object_23.geometry}
            material={materials.Octagon_Material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/assembly-test-dates-transformed.glb');
