/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/cruise-date-bubble.gltf -tT -o CruiseDate.tsx -r /assets/models --keepgroups 
Files: ./public/assets/models/cruise-date-bubble.gltf [14.13KB] > cruise-date-bubble-transformed.glb [89.36KB] (-532%)
*/

import * as THREE from 'three';
import { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import filledVector from '../common/utils/filled-vector';

type GLTFResult = GLTF & {
  nodes: {
    TextPlus011: THREE.Mesh;
    TextPlus011_1: THREE.Mesh;
    TextPlus011_2: THREE.Mesh;
    TextPlus013: THREE.Mesh;
    TextPlus013_1: THREE.Mesh;
    TextPlus013_2: THREE.Mesh;
    TextPlus007003: THREE.Mesh;
    TextPlus007003_1: THREE.Mesh;
    TextPlus007003_2: THREE.Mesh;
    bottomOctagon: THREE.Mesh;
  };
  materials: {
    M_01___Default: THREE.MeshPhysicalMaterial;
    Timeline_Bubble_Material: THREE.MeshStandardMaterial;
    Octagon_Material: THREE.MeshStandardMaterial;
  };
};

export function CruiseDate(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/cruise-date-bubble-transformed.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  const minScaleFactor = filledVector(0.3);
  const maxScaleFactor = filledVector(0.35);
  const isMobile = window.innerWidth < 768;

  useEffect(() => {
    actions.firstMove?.play();
    actions.secondMove?.play();
  }, [actions.firstMove, actions.secondMove]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={isMobile ? minScaleFactor : maxScaleFactor}
      position={isMobile ? [8, -5.5, 10] : [13, -5, 10]}
    >
      <group
        name="FirstSceneDate"
        position={[-15, 8, 0]}
        rotation={[0, -0.395, 0]}
        scale={[0.07, 0.09, 0.08]}
      >
        <mesh
          name="TextPlus007003"
          geometry={nodes.TextPlus007003.geometry}
          material={materials.M_01___Default}
        />
        <mesh
          name="TextPlus007003_1"
          geometry={nodes.TextPlus007003_1.geometry}
          material={materials.Octagon_Material}
        />
        <mesh
          name="TextPlus007003_2"
          geometry={nodes.TextPlus007003_2.geometry}
          material={materials.Timeline_Bubble_Material}
        />
      </group>
      <mesh
        name="bottomOctagon"
        geometry={nodes.bottomOctagon.geometry}
        material={materials.M_01___Default}
        position={[-15, 0, -1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/cruise-date-bubble-transformed.glb');
