/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/debris.gltf -tT -o Debris.tsx -r /assets/models --keepgroups --keepmeshes 
Files: ./public/assets/models/debris.gltf [32.93MB] > debris-transformed.glb [2.29MB] (93%)
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    rock_06: THREE.Mesh;
    Icosphere004: THREE.Mesh;
    Icosphere007: THREE.Mesh;
    Icosphere008: THREE.Mesh;
    Icosphere037: THREE.Mesh;
    Icosphere039: THREE.Mesh;
    Icosphere042: THREE.Mesh;
    Icosphere043: THREE.Mesh;
    Icosphere049: THREE.Mesh;
    Icosphere050: THREE.Mesh;
    rock_04: THREE.Mesh;
    rock_01: THREE.Mesh;
    Icosphere053: THREE.Mesh;
    Icosphere056: THREE.Mesh;
    Icosphere058: THREE.Mesh;
    rock_07: THREE.Mesh;
    Icosphere061: THREE.Mesh;
    rock_03: THREE.Mesh;
    Icosphere065: THREE.Mesh;
    Icosphere067: THREE.Mesh;
    Icosphere083: THREE.Mesh;
    Icosphere084: THREE.Mesh;
    Icosphere085: THREE.Mesh;
    rock_02: THREE.Mesh;
    rock_05: THREE.Mesh;
    Icosphere091: THREE.Mesh;
    Icosphere095: THREE.Mesh;
    Icosphere098: THREE.Mesh;
    Icosphere099: THREE.Mesh;
    Icosphere101: THREE.Mesh;
    Icosphere108: THREE.Mesh;
    Icosphere109: THREE.Mesh;
    Icosphere110: THREE.Mesh;
    Icosphere112: THREE.Mesh;
    Icosphere114: THREE.Mesh;
    Icosphere117: THREE.Mesh;
    Icosphere119: THREE.Mesh;
    Icosphere001: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export function Debris(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    '/assets/models/debris-transformed.glb'
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="rock_06"
          geometry={nodes.rock_06.geometry}
          material={materials['Material.001']}
          position={[-55.108, 3.889, -11.422]}
          rotation={[-1.957, 0.067, -1.122]}
          scale={[1.558, 3.543, 1.558]}
        />
        <mesh
          name="Icosphere004"
          geometry={nodes.Icosphere004.geometry}
          material={materials['Material.001']}
          position={[-35.436, -5.424, -2.119]}
          scale={[0.95, 2.16, 0.95]}
        />
        <mesh
          name="Icosphere007"
          geometry={nodes.Icosphere007.geometry}
          material={materials['Material.001']}
          position={[-48.33, -8.438, 2.35]}
          scale={[0.95, 2.16, 0.95]}
        />
        <mesh
          name="Icosphere008"
          geometry={nodes.Icosphere008.geometry}
          material={materials['Material.001']}
          position={[-17.877, -20.601, -24.986]}
          rotation={[-0.066, -0.201, -1.02]}
          scale={[2.586, 5.879, 2.586]}
        />
        <mesh
          name="Icosphere037"
          geometry={nodes.Icosphere037.geometry}
          material={materials['Material.001']}
          position={[-84.732, -2.527, -5.205]}
          rotation={[-1.292, -0.192, -1.79]}
          scale={[1.045, 2.377, 1.045]}
        />
        <mesh
          name="Icosphere039"
          geometry={nodes.Icosphere039.geometry}
          material={materials['Material.001']}
          position={[-78.279, -8.775, 8.436]}
          scale={[0.637, 1.449, 0.637]}
        />
        <mesh
          name="Icosphere042"
          geometry={nodes.Icosphere042.geometry}
          material={materials['Material.001']}
          position={[-86.928, -10.797, 11.434]}
          scale={[0.637, 1.449, 0.637]}
        />
        <mesh
          name="Icosphere043"
          geometry={nodes.Icosphere043.geometry}
          material={materials['Material.001']}
          position={[-48.645, -19.33, -3.372]}
          rotation={[-0.066, -0.201, -1.02]}
          scale={[-0.918, -2.087, -0.918]}
        />
        <mesh
          name="Icosphere049"
          geometry={nodes.Icosphere049.geometry}
          material={materials['Material.001']}
          position={[48.497, -21.541, 6.593]}
          rotation={[-0.094, -0.815, -0.933]}
          scale={[1.242, 2.823, 1.242]}
        />
        <mesh
          name="Icosphere050"
          geometry={nodes.Icosphere050.geometry}
          material={materials['Material.001']}
          position={[54.973, -25.803, -2.816]}
          scale={[1.242, 2.823, 1.242]}
        />
        <mesh
          name="rock_04"
          geometry={nodes.rock_04.geometry}
          material={materials['Material.001']}
          position={[66.697, -19.556, -15.162]}
          rotation={[0, 0, -2.443]}
          scale={[2.673, 6.077, 2.673]}
        />
        <mesh
          name="rock_01"
          geometry={nodes.rock_01.geometry}
          material={materials['Material.001']}
          position={[24.841, -30.109, -18.545]}
          rotation={[0, 0, -2.795]}
          scale={[-3.04, -6.913, -3.04]}
        />
        <mesh
          name="Icosphere053"
          geometry={nodes.Icosphere053.geometry}
          material={materials['Material.001']}
          position={[38.123, -29.743, 3.025]}
          scale={[1.242, 2.823, 1.242]}
        />
        <mesh
          name="Icosphere056"
          geometry={nodes.Icosphere056.geometry}
          material={materials['Material.001']}
          position={[48.286, -35.766, -1.473]}
          scale={[0.984, 2.238, 0.984]}
        />
        <mesh
          name="Icosphere058"
          geometry={nodes.Icosphere058.geometry}
          material={materials['Material.001']}
          position={[-11.271, -24.774, 0.671]}
          rotation={[0, 0, -1.048]}
          scale={[1.366, 3.106, 1.366]}
        />
        <mesh
          name="rock_07"
          geometry={nodes.rock_07.geometry}
          material={materials['Material.001']}
          position={[-5.361, -27.323, 7.619]}
          rotation={[2.39, 0.884, -2.307]}
          scale={[1, 2, 1]}
        />
        <mesh
          name="Icosphere061"
          geometry={nodes.Icosphere061.geometry}
          material={materials['Material.001']}
          position={[-1.017, -30.182, -0.076]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="rock_03"
          geometry={nodes.rock_03.geometry}
          material={materials['Material.001']}
          position={[0.36, -25.992, -8.358]}
          rotation={[0.4, 0.778, -2.113]}
          scale={[1.793, 4.077, 1.793]}
        />
        <mesh
          name="Icosphere065"
          geometry={nodes.Icosphere065.geometry}
          material={materials['Material.001']}
          position={[37.712, -43.977, -4.452]}
          rotation={[-0.066, -0.201, -1.02]}
          scale={[-1.199, -2.727, -1.199]}
        />
        <mesh
          name="Icosphere067"
          geometry={nodes.Icosphere067.geometry}
          material={materials['Material.001']}
          position={[-14.008, -35.275, 2.208]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere083"
          geometry={nodes.Icosphere083.geometry}
          material={materials['Material.001']}
          position={[-126.894, -24.538, 6.593]}
          rotation={[-0.094, -0.815, -0.933]}
          scale={[1.242, 2.823, 1.242]}
        />
        <mesh
          name="Icosphere084"
          geometry={nodes.Icosphere084.geometry}
          material={materials['Material.001']}
          position={[-108.197, -28.8, -2.816]}
          scale={[1.242, 2.823, 1.242]}
        />
        <mesh
          name="Icosphere085"
          geometry={nodes.Icosphere085.geometry}
          material={materials['Material.001']}
          position={[-106.145, -12.951, -45.377]}
          rotation={[-1.778, 0, 1.036]}
          scale={[2.673, 6.077, 2.673]}
        />
        <mesh
          name="rock_02"
          geometry={nodes.rock_02.geometry}
          material={materials['Material.001']}
          position={[-5.361, -27.323, 7.619]}
          rotation={[2.39, 0.884, -2.307]}
          scale={[-2.872, -6.547, -2.879]}
        />
        <mesh
          name="rock_05"
          geometry={nodes.rock_05.geometry}
          material={materials['Material.001']}
          position={[-85.25, -35.984, -11.402]}
          rotation={[0.449, -0.284, 1.12]}
          scale={[3.379, 7.683, 3.379]}
        />
        <mesh
          name="Icosphere091"
          geometry={nodes.Icosphere091.geometry}
          material={materials['Material.001']}
          position={[-143.906, -27.77, 0.671]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere095"
          geometry={nodes.Icosphere095.geometry}
          material={materials['Material.001']}
          position={[-151.477, -33.895, 17.207]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere098"
          geometry={nodes.Icosphere098.geometry}
          material={materials['Material.001']}
          position={[-175.491, -35.822, 5.225]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere099"
          geometry={nodes.Icosphere099.geometry}
          material={materials['Material.001']}
          position={[-125.459, -46.974, -4.452]}
          rotation={[-0.066, -0.201, -1.02]}
          scale={[-1.199, -2.727, -1.199]}
        />
        <mesh
          name="Icosphere101"
          geometry={nodes.Icosphere101.geometry}
          material={materials['Material.001']}
          position={[-168.673, -38.272, 2.208]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere108"
          geometry={nodes.Icosphere108.geometry}
          material={materials['Material.001']}
          position={[-64.062, -22.594, -40.919]}
          rotation={[-0.066, -0.201, -1.02]}
          scale={[1.729, 3.931, 1.729]}
        />
        <mesh
          name="Icosphere109"
          geometry={nodes.Icosphere109.geometry}
          material={materials['Material.001']}
          position={[-21.343, -41.782, -43.389]}
          rotation={[0, 0, 1.314]}
          scale={[1.607, 3.653, 1.607]}
        />
        <mesh
          name="Icosphere110"
          geometry={nodes.Icosphere110.geometry}
          material={materials['Material.001']}
          position={[-49.865, -36.446, -6.403]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere112"
          geometry={nodes.Icosphere112.geometry}
          material={materials['Material.001']}
          position={[-55.634, -33.691, -13.923]}
          rotation={[-1.292, -0.192, -1.79]}
          scale={[1.366, 3.106, 1.366]}
        />
        <mesh
          name="Icosphere114"
          geometry={nodes.Icosphere114.geometry}
          material={materials['Material.001']}
          position={[-47.201, -41.855, -44.592]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere117"
          geometry={nodes.Icosphere117.geometry}
          material={materials['Material.001']}
          position={[-58.504, -44.498, -1.85]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere119"
          geometry={nodes.Icosphere119.geometry}
          material={materials['Material.001']}
          position={[-72.982, -46.948, -54.822]}
          scale={[0.833, 1.894, 0.833]}
        />
        <mesh
          name="Icosphere001"
          geometry={nodes.Icosphere001.geometry}
          material={materials['Material.001']}
          position={[13.23, -23.216, -51.573]}
          rotation={[1.484, 0.374, 2.006]}
          scale={[1, 2, 1]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/debris-transformed.glb');
