/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/LaunchDate.gltf -tT -o LaunchDate.tsx -r /assets/models 
Files: ./public/assets/models/LaunchDate.gltf [13.34MB] > LaunchDate-transformed.glb [228.34KB] (98%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Mesh } from 'three';
import { useRef } from 'react';
import { Select } from '@react-three/postprocessing';

type GLTFResult = GLTF & {
  nodes: {
    TextPlus001: THREE.Mesh;
  };
  materials: {
    M_01___Default: THREE.MeshPhysicalMaterial;
  };
};

export function LaunchDateModel({
  outline,
  ...props
}: JSX.IntrinsicElements['group'] & { outline?: boolean }) {
  const meshRef = useRef<Mesh>(null);
  const { nodes, materials } = useGLTF(
    '/assets/models/launch-date-model-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <Select enabled={outline}>
        <mesh
          ref={meshRef}
          geometry={nodes.TextPlus001.geometry}
          material={materials.M_01___Default}
          position={[-0.305, 1.535, -0.272]}
          scale={0.025}
        />
      </Select>
    </group>
  );
}

useGLTF.preload('/assets/models/launch-date-model-transformed.glb');
