/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/LaunchPadModel.gltf -tT -o LaunchPadModel.tsx -r /assets/models 
Files: ./public/assets/models/LaunchPadModel.gltf [13.48KB] > LaunchPadModel-transformed.glb [96.7KB] (-617%)
Author: ajd6735 (https://sketchfab.com/ajd6735)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fh-launch-pad-model-4767c3de785e40879db84572f70df159
Title: FH Launch Pad Model
*/
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
  };
  materials: {
    RocketBackSupport: THREE.MeshStandardMaterial;
    MetalBuilding: THREE.MeshPhysicalMaterial;
    Base: THREE.MeshStandardMaterial;
    FalconPedestal: THREE.MeshStandardMaterial;
  };
};

export function LaunchPad(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/models/launch-pad-model-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={0.3}/>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.RocketBackSupport}
        position={[0, -0.591, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.026, 0.026, 0.025]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.MetalBuilding}
        position={[0, -0.591, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.026, 0.026, 0.025]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Base}
        position={[0, -0.591, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.026, 0.026, 0.025]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.FalconPedestal}
        position={[0, -0.591, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.026, 0.026, 0.025]}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/launch-pad-model-transformed.glb');
