/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/LaunchDate.gltf -tT -o LaunchDate.tsx -r /assets/models 
Files: ./public/assets/models/LaunchDate.gltf [4.36MB] > LaunchDate-transformed.glb [277.98KB] (94%)
*/

import * as THREE from 'three';
//import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_Mesh_head_geo001_lambert2SG001: THREE.Mesh;
  };
  materials: {
    ['lambert2SG.001']: THREE.MeshStandardMaterial;
  };
};

{
  /*type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;*/
}

export function LaunchDate(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/models/LaunchDate-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry}
        material={materials['lambert2SG.001']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/LaunchDate-transformed.glb');
