/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/launch-date-model.gltf -tT -o LaunchDateModel.tsx -r /assets/models --keepgroups --keepmeshes 
Files: ./public/assets/models/launch-date-model.gltf [722.48KB] > launch-date-model-transformed.glb [54.73KB] (92%)
*/

import * as THREE from 'three';
import { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    TextPlus001001: THREE.Mesh;
    TextPlus001001_1: THREE.Mesh;
    TextPlus001001_2: THREE.Mesh;
    Cylinder002: THREE.Mesh;
  };
  materials: {
    ['M_01___Default.003']: THREE.MeshPhysicalMaterial;
    ['TimelineBubblePlastic02.001']: THREE.MeshStandardMaterial;
    ['fallback Material.007']: THREE.MeshStandardMaterial;
    ['fallback Material.006']: THREE.MeshStandardMaterial;
  };
};

export function LaunchDateModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/launch-date-model-transformed.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  const minScaleFactor = 0.32;
  const maxScaleFactor = 0.38;
  const isMobile = window.innerWidth < 768;

  useEffect(() => {
    actions.firstMove?.play();
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={isMobile ? minScaleFactor : maxScaleFactor}
      position={isMobile ? [9, -5, 7] : [13, -4.5, 9]}
    >
      <group name="Scene">
        <group
          name="TextPlus001"
          position={[-15, 8, 0]}
          rotation={[0, -0.395, 0]}
          scale={0.07}
        >
          <mesh
            name="TextPlus001001"
            geometry={nodes.TextPlus001001.geometry}
            material={materials['M_01___Default.003']}
          />
          <mesh
            name="TextPlus001001_1"
            geometry={nodes.TextPlus001001_1.geometry}
            material={materials['TimelineBubblePlastic02.001']}
          />
          <mesh
            name="TextPlus001001_2"
            geometry={nodes.TextPlus001001_2.geometry}
            material={materials['fallback Material.007']}
          />
        </group>
        <mesh
          name="Cylinder002"
          geometry={nodes.Cylinder002.geometry}
          material={materials['fallback Material.006']}
          position={[-14.944, -4.982, -0.413]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.006}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/launch-date-model-transformed.glb');
