/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/Launch.gltf -tT -o Launch.tsx -r /assets/models 
Files: ./public/assets/models/Launch.gltf [5.78MB] > Launch-transformed.glb [85.99KB] (99%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    TextPlus001: THREE.Mesh;
  };
  materials: {
    M_01___Default: THREE.MeshStandardMaterial;
  };
};

export function Launch(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/models/launch-scene-name-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TextPlus001.geometry}
        material={materials.M_01___Default}
        position={[0.989, -1.517, 0]}
        scale={0.025}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/launch-scene-name-transformed.glb');
