/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/orbit-date-bubble.gltf -tT -o OrbitDate.tsx -r /assets/models --keepgroups 
Files: ./public/assets/models/orbit-date-bubble.gltf [311.95KB] > orbit-date-bubble-transformed.glb [33.54KB] (89%)
*/

import * as THREE from 'three';
import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    TextPlus007_1: THREE.Mesh;
    TextPlus007_2: THREE.Mesh;
    TextPlus007_3: THREE.Mesh;
    bottomOctagon: THREE.Mesh;
  };
  materials: {
    ['M_01___Default.004']: THREE.MeshPhysicalMaterial;
    Octagon_Material: THREE.MeshStandardMaterial;
    Timeline_Bubble_Material: THREE.MeshStandardMaterial;
    ['M_01___Default.003']: THREE.MeshPhysicalMaterial;
  };
};

export function OrbitDate(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/orbit-date-bubble-transformed.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.SecondDateAction?.play();
  });

  const minScaleFactor = 0.32;
  const maxScaleFactor = 0.4;
  const isMobile = window.innerWidth < 768;

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={isMobile ? minScaleFactor : maxScaleFactor}
    >
      <group name="Scene">
        <group name="Node_3" position={[0.056, 1.217, 0]}>
          <group
            name="TextPlus007"
            position={[-0.34, 7, 0]}
            rotation={[0, -0.395, 0]}
            scale={[0.09, 0.11, 0.075]}
          >
            <mesh
              name="TextPlus007_1"
              geometry={nodes.TextPlus007_1.geometry}
              material={materials['M_01___Default.004']}
            />
            <mesh
              name="TextPlus007_2"
              geometry={nodes.TextPlus007_2.geometry}
              material={materials.Octagon_Material}
            />
            <mesh
              name="TextPlus007_3"
              geometry={nodes.TextPlus007_3.geometry}
              material={materials.Timeline_Bubble_Material}
            />
          </group>
        </group>
        <mesh
          name="bottomOctagon"
          geometry={nodes.bottomOctagon.geometry}
          material={materials['M_01___Default.003']}
          position={[0.058, -0.814, -0.299]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.006}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/orbit-date-bubble-transformed.glb');
