/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/dashed-time-line.gltf -tT -o dashed-time-line.tsx -r /assets/models 
Files: ./public/assets/models/dashed-time-line.gltf [50.23MB] > dashed-time-line-transformed.glb [2.74MB] (95%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    TimelineBuble01: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_31: THREE.Mesh;
    Base: THREE.Mesh;
    mesh_8: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
  };
};

export function TimeLine(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/models/time-line-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TimelineBuble01.geometry}
        material={materials.PaletteMaterial001}
        position={[85.08, 22.86, 11.697]}
        rotation={[0, 0.6, 0]}
        scale={[0.025, 0.03, 0.025]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.PaletteMaterial002}
        position={[-49.242, 35.538, 13.247]}
        rotation={[-Math.PI / 2, 0, -0.209]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Base.geometry}
        material={materials.PaletteMaterial003}
        position={[-53.244, 0.713, 16.039]}
        rotation={[-Math.PI / 2, 0, 0.577]}
        scale={0.028}
      />
      <instancedMesh
        args={[nodes.mesh_8.geometry, materials.PaletteMaterial002, 14]}
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        instanceMatrix={nodes.mesh_8.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload('/assets/models/time-line-transformed.glb');
