/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/assets/models/timeline.gltf -tT -o TimeLine.tsx -r /assets/models --keepgroups --keepmeshes 
Files: ./public/assets/models/time-line.gltf [109.51MB] > timeline-transformed.glb [9.71MB] (91%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Object_5001: THREE.Mesh;
    Cube004: THREE.Mesh;
    PSYCHE_20170116_DEC001: THREE.Mesh;
    mars: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube011: THREE.Mesh;
    TimelineBuble005: THREE.Mesh;
    TimelineBuble005_1: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_2_1: THREE.Mesh;
    Object_2_2: THREE.Mesh;
    Object_2_3: THREE.Mesh;
    Object_2_4: THREE.Mesh;
    Object_2_5: THREE.Mesh;
    Object_2_6: THREE.Mesh;
    Object_2_7: THREE.Mesh;
    Object_2_8: THREE.Mesh;
    Object_2_9: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_23001: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_29001: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11001: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_17001: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_31: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Cylinder001_3: THREE.Mesh;
    Cylinder001_4: THREE.Mesh;
    Cylinder001_5: THREE.Mesh;
    SolarPanelLeft1014: THREE.Mesh;
    SolarPanelLeft1014_1: THREE.Mesh;
    TextPlus002: THREE.Mesh;
    TextPlus002001: THREE.Mesh;
    TextPlus002002: THREE.Mesh;
    TextPlus009: THREE.Mesh;
    TextPlus010: THREE.Mesh;
    TextPlus011: THREE.Mesh;
    TextPlus012: THREE.Mesh;
    TextPlus007: THREE.Mesh;
    TextPlus008: THREE.Mesh;
    TextPlus005: THREE.Mesh;
    TextPlus006: THREE.Mesh;
    TextPlus001: THREE.Mesh;
    TextPlus003: THREE.Mesh;
    TextPlus004: THREE.Mesh;
    Pole: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    ['metal.001']: THREE.MeshStandardMaterial;
    ground: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['fallback_Material.007']: THREE.MeshStandardMaterial;
    Panel_Material: THREE.MeshStandardMaterial;
    FoilMaterial: THREE.MeshStandardMaterial;
    aluminium: THREE.MeshStandardMaterial;
    AlumFoilBack: THREE.MeshStandardMaterial;
    ['Panel_Material.001']: THREE.MeshStandardMaterial;
  };
};

export function TimeLine(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/models/time-line-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={1.5}>
      <group>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.PaletteMaterial001}
          position={[26.302, 1.534, -23.171]}
          rotation={[0.215, 0.561, 0]}
          scale={[29.47, 4.5, 1.255]}
        />
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials['metal.001']}
          position={[-155.416, -18.321, -6.682]}
          scale={[4.059, 1.401, 2.856]}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials.ground}
          position={[-160.88, -20, -6.653]}
          scale={[18, 1, 14]}
        />
        <mesh
          geometry={nodes.PSYCHE_20170116_DEC001.geometry}
          material={materials['Material.007']}
          position={[0.019, 0.96, -8.65]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={12}
        />
        <mesh
          geometry={nodes.mars.geometry}
          material={materials['Material.008']}
          position={[-84.806, 0, 11.041]}
          rotation={[0, 0.768, -0.733]}
          scale={20}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials.PaletteMaterial001}
          position={[0, -61.604, -9.477]}
          scale={3}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials.PaletteMaterial001}
          position={[-79.928, -61.604, 11.793]}
          scale={3}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials.PaletteMaterial001}
          position={[-159.904, -61.604, -9.477]}
          scale={3}
        />
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials.PaletteMaterial001}
          position={[-239.837, -61.604, 11.339]}
          scale={3}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials.PaletteMaterial001}
          position={[-199.958, -61.604, 0.622]}
          rotation={[0, 0.262, 0]}
          scale={[35, 1, 0.5]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials.PaletteMaterial001}
          position={[-40.186, -61.604, 0.622]}
          rotation={[0, 0.262, 0]}
          scale={[35, 1, 0.5]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials.PaletteMaterial001}
          position={[-119.934, -61.604, 0.622]}
          rotation={[0, -0.262, 0]}
          scale={[35, 1, 0.5]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials.PaletteMaterial001}
          position={[-168.574, 22.459, -8.495]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[0.128, 0.391, 0.048]}
        />
        <group position={[0, 0, -9.477]} scale={[0.025, 0.031, 0.009]}>
          <mesh
            geometry={nodes.TimelineBuble005_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <group position={[-80, 0, 10.5]} scale={[0.025, 0.031, 0.009]}>
          <mesh
            geometry={nodes.TimelineBuble005_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <group position={[-160, 0, -9.477]} scale={[0.025, 0.031, 0.009]}>
          <mesh
            geometry={nodes.TimelineBuble005_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <group position={[-240, 0, 10.5]} scale={[0.025, 0.031, 0.009]}>
          s
          <mesh
            geometry={nodes.TimelineBuble005_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <group
          position={[-243.951, -0.736, 3.881]}
          rotation={[-2.772, -0.754, 1.751]}
          scale={0.118}
        >
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.Object_2_1.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.Object_2_4.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.Object_2_6.geometry}
            material={materials.Panel_Material}
          />
          <mesh
            geometry={nodes.Object_2_7.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.Object_2_9.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>

        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial001}
          position={[-155.268, 13.884, -6.308]}
          rotation={[-Math.PI / 2, 0, -0.786]}
          scale={0.034}
        />
        <mesh
          geometry={nodes.Object_11001.geometry}
          material={materials.PaletteMaterial001}
          position={[-155.268, 13.884, -6.308]}
          rotation={[-Math.PI / 2, 0, -0.786]}
          scale={0.034}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.PaletteMaterial001}
          position={[-155.268, 13.884, -6.308]}
          rotation={[-Math.PI / 2, 0, -0.786]}
          scale={0.034}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.PaletteMaterial001}
          position={[-155.268, 13.884, -6.308]}
          rotation={[-Math.PI / 2, 0, -0.786]}
          scale={0.034}
        />
        <mesh
          geometry={nodes.Object_17001.geometry}
          material={materials.PaletteMaterial001}
          position={[-155.268, 13.884, -6.308]}
          rotation={[-Math.PI / 2, 0, -0.786]}
          scale={0.034}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.PaletteMaterial001}
          position={[-155.268, 13.884, -6.308]}
          rotation={[-Math.PI / 2, 0, -0.786]}
          scale={0.034}
        />
        <group
          position={[-62.555, 0.432, 24.21]}
          rotation={[-0.772, 0.653, -2.919]}
          scale={[-0.019, 0.019, 0.011]}
        >
          <mesh
            geometry={nodes.SolarPanelLeft1014.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.SolarPanelLeft1014_1.geometry}
            material={materials['Panel_Material.001']}
          />
        </group>
        <group
          position={[-63.346, -0.56, 23.541]}
          rotation={[-2.276, -0.23, -2.49]}
          scale={[0.58, 0.019, 0.58]}
        >
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.Cylinder001_3.geometry}
            material={materials.FoilMaterial}
          />
          <mesh
            geometry={nodes.Cylinder001_4.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.Cylinder001_5.geometry}
            material={materials.AlumFoilBack}
          />
        </group>
        <mesh
          geometry={nodes.TextPlus002.geometry}
          material={materials.PaletteMaterial001}
          position={[-239.221, 47.789, 9.479]}
          scale={0.2}
        />
        <mesh
          geometry={nodes.TextPlus002001.geometry}
          material={materials.PaletteMaterial001}
          position={[-78.572, 55.584, 10.224]}
          scale={0.2}
        />
        <mesh
          geometry={nodes.TextPlus002002.geometry}
          material={materials.PaletteMaterial001}
          position={[0.075, 54.429, -9.477]}
          scale={0.2}
        />
        <mesh
          geometry={nodes.TextPlus009.geometry}
          material={materials.PaletteMaterial001}
          position={[-78.572, 62.34, 10.224]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus010.geometry}
          material={materials.PaletteMaterial001}
          position={[-78.064, 47.198, 10.224]}
          scale={0.4}
        />
        <mesh
          geometry={nodes.TextPlus011.geometry}
          material={materials.PaletteMaterial001}
          position={[-99.34, 37.585, 10.224]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus012.geometry}
          material={materials.PaletteMaterial001}
          position={[-58.791, 37.564, 10.224]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus007.geometry}
          material={materials.PaletteMaterial001}
          position={[-157.511, 48.532, -9.477]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus008.geometry}
          material={materials.PaletteMaterial001}
          position={[-159.415, 38.278, -9.477]}
          scale={0.4}
        />
        <mesh
          geometry={nodes.TextPlus005.geometry}
          material={materials.PaletteMaterial001}
          position={[-239.221, 54.885, 9.479]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus006.geometry}
          material={materials.PaletteMaterial001}
          position={[-239.221, 39.201, 9.479]}
          scale={0.4}
        />
        <mesh
          geometry={nodes.TextPlus001.geometry}
          material={materials.PaletteMaterial001}
          position={[0.169, 61.377, -9.477]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus003.geometry}
          material={materials.PaletteMaterial001}
          position={[0.072, 47.654, -9.477]}
          scale={0.3}
        />
        <mesh
          geometry={nodes.TextPlus004.geometry}
          material={materials.PaletteMaterial001}
          position={[0.072, 37.868, -9.477]}
          scale={0.4}
        />
        <mesh
          geometry={nodes.Pole.geometry}
          material={materials.PaletteMaterial001}
          position={[-160.687, -19.667, -9.372]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.033}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/time-line-transformed.glb');
