/**
 * Enum representing the name of an AR scene
 */
enum SceneName {
  UNSET,
  ASSEMBLY,
  VIBRATION_TESTING,
  ACOUSTIC_TESTING,
  PACK_ORBITER,
  LAUNCH,
  CRUISE_PANELS,
  CRUISE_THRUSTERS,
  CRUISE_GRAVITY_ASSIST,
  FIRST_ORBIT,
  SECOND_ORBIT,
  THIRD_ORBIT,
  FOURTH_ORBIT
}

export default SceneName;
