name: E2E
on:
  pull_request:
    branches: ['main']
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Download Browsers
        run: npx playwright install
      - name: Test
        run: npm run test:e2e
