name: E2E
on:
  pull_request:
    branches: ['main']
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: 'npm'
      - name: Install NPM Dependencies
        run: npm ci
      - name: Download Browsers
        run: npx playwright install
      - name: Install System Dependencies
        run: npx playwright install-deps
      - name: Test
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
